name: samen1 
description: "De officiÃ«le Samen1 app"
publish_to: none
# De versie bestaat uit 3 nummers: major.minor.patch
# Het build nummer moet bij elke release verhoogd worden
version: 0.5.9+59  # <versie>+<buildnummer>

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  wakelock_plus: ^1.3.2
  package_info_plus: ^8.3.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  url_launcher: ^6.1.14
  video_player: ^2.9.5
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.14.3
  device_info_plus: ^11.4.0
  html: ^0.15.6
  cached_network_image: ^3.3.0
  intl: ^0.20.0
  flutter_html: ^3.0.0
  just_audio: ^0.10.2
  just_audio_background: ^0.0.1-beta.16
  permission_handler: ^12.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo2.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo2.png"